/***************************************************************************
 * Copyright 1996-2025 Synopsys, Inc.
 *
 * This Synopsys software and all associated documentation are proprietary
 * to Synopsys, Inc. and may only be used pursuant to the terms and
 * conditions of a written license agreement with Synopsys, Inc.
 * All other use, reproduction, modification, or distribution of the
 * Synopsys software or the associated documentation is strictly prohibited.
 ***************************************************************************/
 

/***************************************************************************
 * Generated by: TLM Creator
 ***************************************************************************/

// CHECKSUM:2dbc76a26cbeaa2409d4c6214b8296b0de5aac55 

#include <mymodel_0TestHarness.h>



using namespace scml2::testing;



class mymodel_0Test : public mymodel_0TestHarness {

  // Register the test class and all test methods
  SCML2_BEGIN_TESTS(mymodel_0Test);
  SCML2_TEST(testAlwaysSucceeds);
  SCML2_END_TESTS();

  mymodel_0Test() {
  }
  
  // Override this if you want a customize construction of your model under test // ! Only available when not reusing component build in test
  //virtual mymodel_0* create_model_under_test(const char* name) { // ! Only available when not reusing component build in test
  //  return new mymodel_0(name); // ! Only available when not reusing component build in test
  //}

  // Override this if you want to customize construction of your mirror model
  //virtual mymodel_0MirrorBase* create_mirror_model(const char* name) {
  //  return new mymodel_0MirrorBase(name);
  //}
    
  // initialize is called once at the start of the test run, after the model and
  // the mirror model have been created & connected. Initialize the models further here,
  // set up extra connections, set clock periods, ...
  virtual void initialize() {
  }
  
  // Called before running each testcase
  // Reset your model here.
  virtual void setup() {
  }
  
  // Called after running each testcase
  virtual void teardown() {
  }
  
  // Called at the end of the complete testrun
  virtual void shutdown() {
  }
  
  void testAlwaysSucceeds() {
    //enable_logging()
	SCML2_ASSERT_THAT(true, "test always succeeds");
 }  
};



//SCML2_REGISTER_TEST_GROUP_WITH_PARAMETERS(mymodel_0Test, parameter_configurations(parameter_configuration("Default")));
SCML2_REGISTER_TEST_GROUP(mymodel_0Test);


